spring.application.name=campushive-backend

# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d750ehhr0fns73d5a3mg-a.oregon-postgres.render.com:5432/campushive_db
spring.datasource.username=sowmyasri
spring.datasource.password=nSEUJPHiJm96Y5sobkHBbMjrc2L9ARYq
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# Server
server.port=${PORT:8080}

# JWT
jwt.secret=campus_booking_super_secret_key_2024_do_not_share
jwt.expiration=86400000